# Generated by Django 5.2.15 on 2026-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_doc',
            field=models.FileField(blank=True, help_text='Upload business license, ID proof, or any verification document', null=True, upload_to='documents/verification/'),
        ),
    ]
