# Generated by Django 5.2.15 on 2026-07-30 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=1)),
                ('moisture_content_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aroma_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verified_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='farmer.batch')),
                ('product_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'quality verifications',
            },
        ),
    ]
